// Auto-generated by PythScript compiler — do not edit.
const __wasm = await (async () => {
  const imports = {};
  const url = new URL('./similarity.wasm', import.meta.url);
  const isNode = typeof globalThis.process !== 'undefined'
    && globalThis.process.versions != null
    && typeof globalThis.process.versions.node === 'string';
  if (isNode) {
    const { readFile } = await import('node:fs/promises');
    const { fileURLToPath } = await import('node:url');
    const bytes = await readFile(fileURLToPath(url));
    return (await WebAssembly.instantiate(bytes, imports)).instance.exports;
  }
  if (typeof WebAssembly.instantiateStreaming === 'function') {
    return (await WebAssembly.instantiateStreaming(fetch(url), imports)).instance.exports;
  }
  const bytes = await fetch(url).then(r => r.arrayBuffer());
  return (await WebAssembly.instantiate(bytes, imports)).instance.exports;
})();

export function cosine(a, b) {
  return __wasm.cosine(__list_to_wasm(a), __list_to_wasm(b));
}

export function dot(a, b) {
  return __wasm.dot(__list_to_wasm(a), __list_to_wasm(b));
}

export function norm(a) {
  return __wasm.norm(__list_to_wasm(a));
}
